INSERT INTO `app_config` (`configkey`, `configname`, `configdescription`, `datatype`, `value`, `typekey`, `typename`, `description`, `created`, `modified`, `saasId`, `ishidden`) VALUES ('coinName', '币种名称', '币种名称', '1', 'ABC', 'LC_Rules_Coin_Config', '平台发币信息', '平台发币信息', '2019-08-12 15:58:09', '2019-08-12 15:15:13', 'hurong_system', '0');
INSERT INTO `app_config` (`configkey`, `configname`, `configdescription`, `datatype`, `value`, `typekey`, `typename`, `description`, `created`, `modified`, `saasId`, `ishidden`) VALUES ('coinCode', '币种Code', '币种Code', '1', 'ABC', 'LC_Rules_Coin_Config', '平台发币信息', '平台发币信息', '2019-08-12 15:58:09', '2019-08-12 15:58:09', 'hurong_system', '0');
INSERT INTO `app_config` (`configkey`, `configname`, `configdescription`, `datatype`, `value`, `typekey`, `typename`, `description`, `created`, `modified`, `saasId`, `ishidden`) VALUES ('issuePrice', '货币价格(USDT)', '货币价格(USDT)', '1', '10', 'LC_Rules_Coin_Config', '平台发币信息', '平台发币信息', '2019-08-12 15:58:09', '2019-08-12 15:58:09', 'hurong_system', '0');
/*INSERT INTO `app_config` (`configkey`, `configname`, `configdescription`, `datatype`, `value`, `typekey`, `typename`, `description`, `created`, `modified`, `saasId`, `ishidden`) VALUES ('convertRate', '折算汇率(%)', '折算汇率(%)', '1', '10', 'LC_Rules_Coin_Config', '平台发币信息', '平台发币信息', '2019-08-12 15:58:09', '2019-08-12 15:58:09', 'hurong_system', '0');*/

INSERT INTO `app_config` (`configkey`, `configname`, `configdescription`, `datatype`, `value`, `typekey`, `typename`, `description`, `created`, `modified`, `saasId`, `ishidden`) VALUES ('extractStartTime', '提币开始时间', '提币开始时间', '5', '00:00:00', 'LC_Extract_Time_Config', '提币时间配置', '提币时间配置', '2019-08-12 15:58:09', '2019-08-12 15:58:09', 'hurong_system', '0');
INSERT INTO `app_config` (`configkey`, `configname`, `configdescription`, `datatype`, `value`, `typekey`, `typename`, `description`, `created`, `modified`, `saasId`, `ishidden`) VALUES ('extractEndTime', '提币结束时间', '提币结束时间', '5', '23:59:59', 'LC_Extract_Time_Config', '提币时间配置', '提币时间配置', '2019-08-12 15:58:09', '2019-08-12 15:58:09', 'hurong_system', '0');
INSERT INTO `app_config` (`configkey`, `configname`, `configdescription`, `datatype`, `value`, `typekey`, `typename`, `description`, `created`, `modified`, `saasId`, `ishidden`) VALUES ('extractNum', '提币次数', '提币次数', '1', '1', 'LC_Extract_Time_Config', '提币时间配置', '提币时间配置', '2019-08-12 15:58:09', '2019-08-12 15:58:09', 'hurong_system', '0');

INSERT INTO `app_config` (`configkey`, `configname`, `configdescription`, `datatype`, `value`, `typekey`, `typename`, `description`, `created`, `modified`, `saasId`, `ishidden`) VALUES ('exchangeStartTime', '兑换开始时间', '兑换开始时间', '5', '00:00:00', 'LC_Exchange_Time_Config', '兑换时间配置', '兑换时间配置', '2020-09-08 15:58:09', '2020-09-08 15:58:09', 'hurong_system', '0');
INSERT INTO `app_config` (`configkey`, `configname`, `configdescription`, `datatype`, `value`, `typekey`, `typename`, `description`, `created`, `modified`, `saasId`, `ishidden`) VALUES ('exchangeEndTime', '兑换结束时间', '兑换结束时间', '5', '23:59:59', 'LC_Exchange_Time_Config', '兑换时间配置', '兑换时间配置', '2020-09-08 15:58:09', '2020-09-08 15:58:09', 'hurong_system', '0');

INSERT INTO `app_config` (`configkey`, `configname`, `configdescription`, `datatype`, `value`, `typekey`, `typename`, `description`, `created`, `modified`, `saasId`, `ishidden`) VALUES ('investStartTime', '理财开始时间', '理财开始时间', '5', '09:00:00', 'LC_Invest_Time_Config', '理财时间配置', '理财时间配置', '2020-09-08 15:58:09', '2020-09-08 15:58:09', 'hurong_system', '0');
INSERT INTO `app_config` (`configkey`, `configname`, `configdescription`, `datatype`, `value`, `typekey`, `typename`, `description`, `created`, `modified`, `saasId`, `ishidden`) VALUES ('investEndTime', '理财结束时间', '理财结束时间', '5', '23:59:59', 'LC_Invest_Time_Config', '理财时间配置', '理财时间配置', '2020-09-08 15:58:09', '2020-09-08 15:58:09', 'hurong_system', '0');



INSERT INTO `app_config` (`configkey`, `configname`, `configdescription`, `datatype`, `value`, `typekey`, `typename`, `description`, `created`, `modified`, `saasId`, `ishidden`) VALUES ('minInvest', '最小投资金额(USDT)', '最小投资金额(USDT)', '1', '0', 'LC_Invest_Range_Config', '投资区间设置', '投资区间设置', '2019-08-12 15:58:09', '2019-08-12 15:58:09', 'hurong_system', '0');
INSERT INTO `app_config` (`configkey`, `configname`, `configdescription`, `datatype`, `value`, `typekey`, `typename`, `description`, `created`, `modified`, `saasId`, `ishidden`) VALUES ('maxInvest', '最大投资金额(USDT)', '最大投资金额(USDT)', '1', '0', 'LC_Invest_Range_Config', '投资区间设置', '投资区间设置', '2019-08-12 15:58:09', '2019-08-12 15:58:09', 'hurong_system', '0');
INSERT INTO `app_config` (`configkey`, `configname`, `configdescription`, `datatype`, `value`, `typekey`, `typename`, `description`, `created`, `modified`, `saasId`, `ishidden`) VALUES ('minManageMoney', '最小理财金额(USDT)', '最小理财金额(USDT)', '1', '0', 'LC_Invest_Range_Config', '投资区间设置', '投资区间设置', '2019-08-12 15:58:09', '2019-08-12 15:58:09', 'hurong_system', '0');



INSERT INTO `app_config` (`configkey`, `configname`, `configdescription`, `datatype`, `value`, `typekey`, `typename`, `description`, `created`, `modified`, `saasId`, `ishidden`) VALUES ('mondayGainsRatio', '周一收益比例(%)', '周一收益比例(%)', '1', '0', 'LC_Static_Gains_Config', '静态收益设置', '静态收益设置', '2019-08-12 15:58:09', '2019-08-12 15:58:09', 'hurong_system', '0');
INSERT INTO `app_config` (`configkey`, `configname`, `configdescription`, `datatype`, `value`, `typekey`, `typename`, `description`, `created`, `modified`, `saasId`, `ishidden`) VALUES ('tuesdayGainsRatio', '周二收益比例(%)', '周二收益比例(%)', '1', '0', 'LC_Static_Gains_Config', '静态收益设置', '静态收益设置', '2019-08-12 15:58:09', '2019-08-12 15:58:09', 'hurong_system', '0');
INSERT INTO `app_config` (`configkey`, `configname`, `configdescription`, `datatype`, `value`, `typekey`, `typename`, `description`, `created`, `modified`, `saasId`, `ishidden`) VALUES ('wednesdayGainsRatio', '周三收益比例(%)', '周三收益比例(%)', '1', '0', 'LC_Static_Gains_Config', '静态收益设置', '静态收益设置', '2019-08-12 15:58:09', '2019-08-12 15:58:09', 'hurong_system', '0');
INSERT INTO `app_config` (`configkey`, `configname`, `configdescription`, `datatype`, `value`, `typekey`, `typename`, `description`, `created`, `modified`, `saasId`, `ishidden`) VALUES ('thursdayGainsRatio', '周四收益比例(%)', '周四收益比例(%)', '1', '0', 'LC_Static_Gains_Config', '静态收益设置', '静态收益设置', '2019-08-12 15:58:09', '2019-08-12 15:58:09', 'hurong_system', '0');
INSERT INTO `app_config` (`configkey`, `configname`, `configdescription`, `datatype`, `value`, `typekey`, `typename`, `description`, `created`, `modified`, `saasId`, `ishidden`) VALUES ('fridayGainsRatio', '周五收益比例(%)', '周五收益比例(%)', '1', '0', 'LC_Static_Gains_Config', '静态收益设置', '静态收益设置', '2019-08-12 15:58:09', '2019-08-12 15:58:09', 'hurong_system', '0');
INSERT INTO `app_config` (`configkey`, `configname`, `configdescription`, `datatype`, `value`, `typekey`, `typename`, `description`, `created`, `modified`, `saasId`, `ishidden`) VALUES ('saturdayGainsRatio', '周六收益比例(%)', '周六收益比例(%)', '1', '0', 'LC_Static_Gains_Config', '静态收益设置', '静态收益设置', '2019-08-12 15:58:09', '2019-08-12 15:58:09', 'hurong_system', '0');
INSERT INTO `app_config` (`configkey`, `configname`, `configdescription`, `datatype`, `value`, `typekey`, `typename`, `description`, `created`, `modified`, `saasId`, `ishidden`) VALUES ('weekdayGainsRatio', '周日收益比例(%)', '周日收益比例(%)', '1', '0', 'LC_Static_Gains_Config', '静态收益设置', '静态收益设置', '2019-08-12 15:58:09', '2019-08-12 15:58:09', 'hurong_system', '0');

INSERT INTO `app_config` (`configkey`, `configname`, `configdescription`, `datatype`, `value`, `typekey`, `typename`, `description`, `created`, `modified`, `saasId`, `ishidden`) VALUES ('maxNumberPlies', '最高可拿代数', '最高可拿代数', '1', '0', 'LC_See_Award_Config', '见点奖设置', '见点奖设置', '2019-08-12 15:58:09', '2019-08-12 15:58:09', 'hurong_system', '0');
INSERT INTO `app_config` (`configkey`, `configname`, `configdescription`, `datatype`, `value`, `typekey`, `typename`, `description`, `created`, `modified`, `saasId`, `ishidden`) VALUES ('awardRatio', '奖励比例(%)', '奖励比例(%)', '1', '0', 'LC_See_Award_Config', '见点奖设置', '见点奖设置', '2019-08-12 15:58:09', '2019-08-12 15:58:09', 'hurong_system', '0');

INSERT INTO `app_config` (`configkey`, `configname`, `configdescription`, `datatype`, `value`, `typekey`, `typename`, `description`, `created`, `modified`, `saasId`, `ishidden`) VALUES ('maxNumberPlies', '最高可拿代数', '最高可拿代数', '1', '0', 'LC_Manage_Award_Config', '管理奖设置', '管理奖设置', '2019-08-12 15:58:09', '2019-08-12 15:58:09', 'hurong_system', '0');
INSERT INTO `app_config` (`configkey`, `configname`, `configdescription`, `datatype`, `value`, `typekey`, `typename`, `description`, `created`, `modified`, `saasId`, `ishidden`) VALUES ('oneAwardRatio', '一代奖励比例(%)', '一代奖励比例(%)', '1', '0', 'LC_Manage_Award_Config', '管理奖设置', '管理奖设置', '2019-08-12 15:58:09', '2019-08-12 15:58:09', 'hurong_system', '0');
INSERT INTO `app_config` (`configkey`, `configname`, `configdescription`, `datatype`, `value`, `typekey`, `typename`, `description`, `created`, `modified`, `saasId`, `ishidden`) VALUES ('twoAwardRatio', '二代奖励比例(%)', '二代奖励比例(%)', '1', '0', 'LC_Manage_Award_Config', '管理奖设置', '管理奖设置', '2019-08-12 15:58:09', '2019-08-12 15:58:09', 'hurong_system', '0');
INSERT INTO `app_config` (`configkey`, `configname`, `configdescription`, `datatype`, `value`, `typekey`, `typename`, `description`, `created`, `modified`, `saasId`, `ishidden`) VALUES ('threeAwardRatio', '三代以上奖励比例(%)', '三代以上励比例(%)', '1', '0', 'LC_Manage_Award_Config', '管理奖设置', '管理奖设置', '2019-08-12 15:58:09', '2019-08-12 15:58:09', 'hurong_system', '0');

/*~~~~个人等级初始化~~~~*/
INSERT INTO lc_level_config (id,levelName,sort) VALUES (1,'v1',1);
INSERT INTO lc_level_config (id,levelName,sort) VALUES (2,'v2',2);
INSERT INTO lc_level_config (id,levelName,sort) VALUES (3,'v3',3);

/*~~~~社区等级初始化~~~~*/
INSERT INTO `lc_team_level_config` (`id`,`teamLevelName`, `teamSort`) VALUES ('1','t1', '1');
INSERT INTO `lc_team_level_config` (`id`,`teamLevelName`, `teamSort`) VALUES ('2','t2', '2');
INSERT INTO `lc_team_level_config` (`id`,`teamLevelName`, `teamSort`) VALUES ('3','t3', '3');
INSERT INTO `lc_team_level_config` (`id`,`teamLevelName`, `teamSort`) VALUES ('4','t4', '4');

INSERT INTO `app_config`(`configid`, `configkey`, `configname`, `configdescription`, `datatype`, `value`, `typekey`, `typename`, `description`, `created`, `modified`, `saasId`, `ishidden`) VALUES (429, 'klinedataurl', '请求地址', '多币种实时详情', 1, 'http://39.107.88.70/api/hryr/dc/getCurrencyInfo', 'realtimepriceinfoconfig', '请求地址', '请求地址', '2018-09-06 14:50:42', '2018-12-20 13:38:48', 'hurong_system', 0);
INSERT INTO `app_config`(`configid`, `configkey`, `configname`, `configdescription`, `datatype`, `value`, `typekey`, `typename`, `description`, `created`, `modified`, `saasId`, `ishidden`) VALUES (430, 'businessNumber', '商户号', '', 1, '8aff8da0d3db45478b782ea57e6eed7e', 'realtimepriceinfoconfig', '商户号', '商户号', '2018-09-06 14:50:42', '2018-12-20 13:38:48', 'hurong_system', 0);
INSERT INTO `app_config`(`configid`, `configkey`, `configname`, `configdescription`, `datatype`, `value`, `typekey`, `typename`, `description`, `created`, `modified`, `saasId`, `ishidden`) VALUES (431, 'publickey', '公钥', '', 1, 'MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCt+sHJjBYkYpT6ai2V1Cc0rx71RAlaX9MJBdwo7gJkp9NI0N6qy9CbPNfeVBpekjfIB1JQkHW4ypeYAuGMzC5uoMcJ169Xi8uaS2OIhiYYYiX/zCJQPKF5b+7EdQQBQfv7EAlMfF+5sdi9RJQPLExRlUyEJNYHiHTTwWQRbhKNKQIDAQAB', 'realtimepriceinfoconfig', '公钥', '公钥', '2018-09-06 14:50:42', '2018-12-20 13:38:48', 'hurong_system', 0);
INSERT INTO `app_config`(`configid`, `configkey`, `configname`, `configdescription`, `datatype`, `value`, `typekey`, `typename`, `description`, `created`, `modified`, `saasId`, `ishidden`) VALUES (432, 'privatekey', '私钥', '', 1, 'MIICdgIBADANBgkqhkiG9w0BAQEFAASCAmAwggJcAgEAAoGBAK36wcmMFiRilPpqLZXUJzSvHvVECVpf0wkF3CjuAmSn00jQ3qrL0Js8195UGl6SN8gHUlCQdbjKl5gC4YzMLm6gxwnXr1eLy5pLY4iGJhhiJf/MIlA8oXlv7sR1BAFB+/sQCUx8X7mx2L1ElA8sTFGVTIQk1geIdNPBZBFuEo0pAgMBAAECgYBhlU+Sk49r0xuKpXlyG2/uHfd4TDQOy8abvfyxvGX9PSDGK9lo5S7Zk7Pk0TmFJ/A/stOZup09C+0hZyRJi9DScX5ec3FArYvz/70avF0D2kAjuWLDjCIsgI8zOvmkVTl5Zdkn+pqKxh/ltMeFAVz4/URzG4ouTCF0JosVyzJqMQJBANOX2gYMt9roto2m5t2/pQ31eXCb3bfBwQPsCgo2fSytpCadU4QIqZrx0mbsJezRPYm76cJRD/iZDLYM2HGXe6UCQQDSfg7CwTBuVpOSDJeQNUDZk5P2SfviG08vwDTz1v/IoXCfJpwIjmfFpuyBNBi8+/a7GLQRtfnPKmGjLmjZi+Q1AkBKdu5rop4xlCRqxYoKEB/uQa1zS+dDfBSJZNBDt9lll9ZlIIj7tnC57tC1F/Zg2WJmzpL9p7mPK42lo++oSj9hAkA2q+Mtlnv7zKTbpEWhgRNs77XYnHK90ZYJswSN6OPauoPD8oVIe6RcY/S9wkhCnbcB9XKfvwI5WqqtdZpqFrmZAkEAzkKTjW+zU5Pm5Pfg63lq0N/qWNGnI9NIrWTGbu6/P5s0U45+Iyi21cSUqQCJrhxL+VS0vtGVh1mVJY+LbChyiw==', 'realtimepriceinfoconfig', '私钥', '私钥', '2018-09-06 14:50:42', '2018-12-20 13:38:48', 'hurong_system', 0);

/*~~~~生态入驻规则设置~~~~*/
INSERT INTO `app_config` (`configkey`, `configname`, `configdescription`, `datatype`, `value`, `typekey`, `typename`, `description`, `created`, `modified`, `saasId`, `ishidden`) VALUES ('acceptAddress', '收款地址', '收款地址', '1', '', 'LC_Ecolog_enter_Config', '生态入驻规则设置', '生态入驻规则设置', '2020-06-05 15:58:09', '2020-06-05 15:58:09', 'hurong_system', '0');
INSERT INTO `app_config` (`configkey`, `configname`, `configdescription`, `datatype`, `value`, `typekey`, `typename`, `description`, `created`, `modified`, `saasId`, `ishidden`) VALUES ('validityDate', '保证金有效天数（天）', '保证金有效天数（天）', '1', '', 'LC_Ecolog_enter_Config', '生态入驻规则设置', '生态入驻规则设置', '2020-06-05 15:58:09', '2020-06-05 15:58:09', 'hurong_system', '0');