module.exports={
  NODE_ENV:'"cqlic"',
  BASE_API:'"http://www.bbgo.vip/app"',
  SOCKET_URL: '"ws://www.bbgo.vip:99/"',
  NIO_URL: '"ws://www.bbgo.vip/deep"',
  SOCKET_CONTRACT: '"ws://www.bbgo.vip/app/ct"',
  PATH_IMG: '"https://cqlic-exchange-public.oss-ap-northeast-1.aliyuncs.com/"',
  Fabi_Flag:'"true"',
  wakuang_Flag:'"false"',
  bankbtn_Flag:'"true"',
  lianxi_Flag:'"true"',
  app_Flag:'"true"',
   jichushezhi_Flag:'"true"',
   c2c_Flag:'"true"',
   dfc_Flag:'"false"',
   contracttrade_Flag:'"true"',
   contracttrade_chy_Flag:'"true"',
  contracttrade_yx_Flag:'"false"',
  hongbao_Flag:'"false"',
  licai_Flag:'"false"',
  shubilicai_Flag:'"false"',
    bibitrade_Flag:'"true"',
  conduct_Flag:'"true"',
options_Flag:'"false"',
  vue_appDown_url:'"http://www.bbgo.vip/#/"',
  heyueweituo_Flah:'"false"',
  kuailegou_Flag:'"true"',
  partner_Flag:'"false"',
  ptbTrading_Flag:'"false"',
  matchAccountflag:'"false"',
  project_name:'"smea"',
  contractedtwo_Flag:'"false"',
  otcWhite_flag:'"true"',
newOtc_flag:'"true"',
OTC_API:'"http://www.bbgo.vip/otc"',//otcÏîÄ¿Â·¾¶
SOCKET_OTC:'"ws://www.bbgo.vip/otc/otcChat"',
sanShengRegEmail_Flag:'"false"',
sanShengYong_Flag:'"true"',
showPhone_Flag:'"true"'
}
